# Generated by Django 5.0.2 on 2026-06-19 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherdata',
            name='wind_dir',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='wind_mph',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='wind_relative',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
