# Generated by Django 5.0.2 on 2026-06-13 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0014_pitcher_throws_and_hitter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picks', to='games.game')),
                ('picked_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picks', to='games.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-game__date', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='pick',
            constraint=models.UniqueConstraint(fields=('user', 'game'), name='unique_user_game_pick'),
        ),
    ]
