# Generated by Django 5.0.2 on 2026-03-04 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='losses',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='win_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='wins',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
