# Generated by Django 5.0.2 on 2026-03-04 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_team_losses_team_win_pct_team_wins'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='last10_losses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='last10_wins',
            field=models.IntegerField(default=0),
        ),
    ]
