# Generated by Django 5.0.2 on 2026-03-06 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_team_last10_losses_team_last10_wins'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitcher',
            name='innings_pitched',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='pitcher',
            name='strikeouts',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pitcher',
            name='walks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pitcher',
            name='whip',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
