# Generated by Django 5.0.2 on 2026-03-06 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_pitcher_innings_pitched_pitcher_strikeouts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='start_time_utc',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
