# Generated by Django 5.0.2 on 2026-04-27 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_team_abbreviation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reliever',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mlb_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('season_appearances', models.IntegerField(default=0)),
                ('saves', models.IntegerField(default=0)),
                ('holds', models.IntegerField(default=0)),
                ('pitched_yesterday', models.BooleanField(default=False)),
                ('yesterday_pitches', models.IntegerField(blank=True, null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relievers', to='games.team')),
            ],
            options={
                'ordering': ['-season_appearances'],
            },
        ),
    ]
