# Generated by Django 5.0.2 on 2026-04-27 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_reliever'),
    ]

    operations = [
        migrations.AddField(
            model_name='reliever',
            name='era',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
