# Generated by Django 5.0.2 on 2026-05-01 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_reliever_era'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='away_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='away_starter_runs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='home_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='home_starter_runs',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
