# Generated by Django 5.0.2 on 2026-05-01 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_game_away_score_game_away_starter_runs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='away_starter_innings',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='home_starter_innings',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
