# Generated by Django 5.0.2 on 2026-06-23 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0014_pitcher_throws_and_hitter'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerIDMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normalized_name', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('mlb_id', models.IntegerField()),
                ('bats', models.CharField(blank=True, max_length=1, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_ids', to='games.team')),
            ],
            options={
                'unique_together': {('normalized_name', 'team')},
            },
        ),
    ]
