# Generated by Django 5.0.2 on 2026-06-23 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0015_playeridmap'),
    ]

    operations = [
        migrations.AddField(
            model_name='hitter',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hitter',
            name='mlb_id',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='hitter',
            unique_together={('mlb_id', 'date')},
        ),
    ]
