# Generated by Django 5.0.2 on 2026-06-23 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0016_hitter_date_alter_hitter_mlb_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hitter',
            name='position',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
