# Generated by Django 5.0.2 on 2026-06-24 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0017_hitter_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitcher',
            name='away_avg',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='pitcher',
            name='away_bf',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pitcher',
            name='away_ops',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='pitcher',
            name='home_avg',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='pitcher',
            name='home_bf',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pitcher',
            name='home_ops',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='pitcher',
            name='vs_l_avg',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='pitcher',
            name='vs_l_bf',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pitcher',
            name='vs_l_ops',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='pitcher',
            name='vs_r_avg',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='pitcher',
            name='vs_r_bf',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pitcher',
            name='vs_r_ops',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
