# Generated by Django 5.0.2 on 2026-06-26 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0018_pitcher_away_avg_pitcher_away_bf_pitcher_away_ops_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='postponed',
            field=models.BooleanField(default=False),
        ),
    ]
