# Generated by Django 5.0.2 on 2026-07-11 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0019_game_postponed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='last7_avg',
            new_name='last14_avg',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='last7_runs',
            new_name='last14_runs',
        ),
        migrations.AddField(
            model_name='team',
            name='last14_ops',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
