# Generated by Django 5.0.2 on 2026-07-11 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0020_rename_last7_avg_team_last14_avg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='last7_avg',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='last7_ops',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='last7_runs',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
