# Generated by Django 5.0.2 on 2026-07-12 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0021_team_last7_avg_team_last7_ops_team_last7_runs'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='last14_games',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='last7_games',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
