# Generated by Django 5.0.2 on 2026-08-12 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0022_team_last14_games_team_last7_games'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='away_moneyline',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='home_moneyline',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
