# Generated by Django 5.0.2 on 2026-08-21 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0023_game_away_moneyline_game_home_moneyline'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitcher',
            name='losses',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pitcher',
            name='wins',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
